// <auto-generated />
using System;
using ICE_TASK_3.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICE_TASK_3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231023211037_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ICE_TASK_3.Model.Cow", b =>
                {
                    b.Property<int>("CowTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CowTag"));

                    b.Property<double>("AgeInMonth")
                        .HasColumnType("float");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("CowCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmID")
                        .HasColumnType("int");

                    b.Property<int?>("InvestmentPortfolioInvestmentNum")
                        .HasColumnType("int");

                    b.HasKey("CowTag");

                    b.HasIndex("FarmID");

                    b.HasIndex("InvestmentPortfolioInvestmentNum");

                    b.ToTable("Cows");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.Farm", b =>
                {
                    b.Property<int>("FarmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmID"));

                    b.Property<int?>("CowTag")
                        .HasColumnType("int");

                    b.Property<string>("FarmAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FarmID");

                    b.HasIndex("CowTag");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.InvestmentPortfolio", b =>
                {
                    b.Property<int>("InvestmentNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestmentNum"));

                    b.Property<int>("CowTag")
                        .HasColumnType("int");

                    b.Property<double>("Est_Payout")
                        .HasColumnType("float");

                    b.Property<double>("InvestmentPeriod")
                        .HasColumnType("float");

                    b.Property<int>("InvestorID")
                        .HasColumnType("int");

                    b.Property<double>("MaintenaceFeePerMonth")
                        .HasColumnType("float");

                    b.Property<double>("MaintenanceSavingsRate")
                        .HasColumnType("float");

                    b.Property<double>("RIO_Rate")
                        .HasColumnType("float");

                    b.Property<double>("TAX_Rate")
                        .HasColumnType("float");

                    b.HasKey("InvestmentNum");

                    b.HasIndex("CowTag");

                    b.HasIndex("InvestorID");

                    b.ToTable("InvestmentPortfolios");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.Investor", b =>
                {
                    b.Property<int>("InvestorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestorID"));

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<string>("I_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvestmentPortfolioInvestmentNum")
                        .HasColumnType("int");

                    b.Property<string>("InvestorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxNumber")
                        .HasColumnType("int");

                    b.HasKey("InvestorID");

                    b.HasIndex("InvestmentPortfolioInvestmentNum");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.Cow", b =>
                {
                    b.HasOne("ICE_TASK_3.Model.Farm", "Farm")
                        .WithMany("Cows")
                        .HasForeignKey("FarmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICE_TASK_3.Model.InvestmentPortfolio", null)
                        .WithMany("Cows")
                        .HasForeignKey("InvestmentPortfolioInvestmentNum");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.Farm", b =>
                {
                    b.HasOne("ICE_TASK_3.Model.Cow", null)
                        .WithMany("Farms")
                        .HasForeignKey("CowTag");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.InvestmentPortfolio", b =>
                {
                    b.HasOne("ICE_TASK_3.Model.Cow", "Cow")
                        .WithMany("InvestmentPortfolios")
                        .HasForeignKey("CowTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICE_TASK_3.Model.Investor", "Investor")
                        .WithMany("InvestmentPortfolios")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cow");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.Investor", b =>
                {
                    b.HasOne("ICE_TASK_3.Model.InvestmentPortfolio", null)
                        .WithMany("Investors")
                        .HasForeignKey("InvestmentPortfolioInvestmentNum");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.Cow", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("InvestmentPortfolios");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.Farm", b =>
                {
                    b.Navigation("Cows");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.InvestmentPortfolio", b =>
                {
                    b.Navigation("Cows");

                    b.Navigation("Investors");
                });

            modelBuilder.Entity("ICE_TASK_3.Model.Investor", b =>
                {
                    b.Navigation("InvestmentPortfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
